version: '3.7'

services:
  bot:
    image: ghcr.io/efrei-craft/efrei-craft-bot:main
    environment:
      TOKEN: ${TOKEN}
      APPID: ${APPID}
      ANIMUS_BASE_URL: "https://api.efreicraft.fr/"
      ANIMUS_API_KEY: ${ANIMUS_API_KEY}
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    extra_hosts:
      - "api.efreicraft.fr:10.10.51.120"